const snippets = [
    {
      id: 1,
      lines: [
        'import java.util.Scanner;',
        'public class SumCalculator {',
        '    public static void main(String[] args) {',
        '        Scanner scanner = new Scanner(System.in);',
        '        System.out.println("Introduceți numărul maxim pentru calculul sumei:");',
        '        int maxNumber = scanner.nextInt();',
        '        int sum = calculateSum(maxNumber);',
        '        System.out.println("Suma numerelor de la 1 la " + maxNumber + " este: " + sum);',
        '        scanner.close();',
        '    }',
        '    public static int calculateSum(int maxNumber) {',
        '        int sum = 0;',
        '        for (int i = 1; i <= maxNumber; i++) {',
        '            sum += i;',
        '        }',
        '        return sum;',
        '    }',
        '}',
      ],
    },
    {
        id: 2,
        lines: [
          'import java.util.Scanner;',
          'public class SumCalculator {',
          '    public static void main(String[] args) {',
          '        Scanner scanner = new Scanner(System.in);',
          '        System.out.println("Introduceți numărul maxim pentru calculul sumei:");',
          '        int maxNumber = scanner.nextInt();',
          '        int sum = calculateSum(maxNumber);',
          '        System.out.println("Suma numerelor de la 1 la " + maxNumber + " este: " + sum);',
          '        scanner.close();',
          '    }',
          '    public static int calculateSum(int maxNumber) {',
          '        int sum = 0;',
          '        for (int i = 1; i <= maxNumber; i++) {',
          '            sum += i;',
          '        }',
          '        return sum;',
          '    }',
          '}',
        ],
      },
      {
        id: 3,
        lines: [
          'import java.util.Scanner;',
          'public class SumCalculator {',
          '    public static void main(String[] args) {',
          '        Scanner scanner = new Scanner(System.in);',
          '        System.out.println("Introduceți numărul maxim pentru calculul sumei:");',
          '        int maxNumber = scanner.nextInt();',
          '        int sum = calculateSum(maxNumber);',
          '        System.out.println("Suma numerelor de la 1 la " + maxNumber + " este: " + sum);',
          '        scanner.close();',
          '    }',
          '    public static int calculateSum(int maxNumber) {',
          '        int sum = 0;',
          '        for (int i = 1; i <= maxNumber; i++) {',
          '            sum += i;',
          '        }',
          '        return sum;',
          '    }',
          '}',
        ],
      },
  ];
  
  export default snippets;
  