const snippets = [
    {
      id: 1,
      lines: [
        'import java.util.Scanner;',
        'public class SumCalculator {',
        'public static void main(String[] args) {',
        'Scanner scanner = new Scanner(System.in);',
        'System.out.println("Introduceți numărul maxim pentru calculul sumei:");',
        'int maxNumber = scanner.nextInt();',
        'int sum = calculateSum(maxNumber);',
        'System.out.println("Suma numerelor de la 1 la " + maxNumber + " este: " + sum);',
        ' scanner.close();',
        '    }',
        ' public static int calculateSum(int maxNumber) {',
        'int sum = 0;',
        'for (int i = 1; i <= maxNumber; i++) {',
        'sum += i;',
        '    }',
        'return sum;',
        '    }',
        '}',
      ],
    },
    {
      id: 2,
      lines: [
        'import java.util.Scanner;',
        'public class PrimeCheck {',
        '  public static void main(String[] args) {',
        '    Scanner input = new Scanner(System.in);',
        '    System.out.print("Introdu un număr: ");',
        '    int num = input.nextInt();',
        '    boolean isPrime = true;',
        '    if (num <= 1) isPrime = false;',
        '    for (int i = 2; i <= Math.sqrt(num); i++) {',
        '      if (num % i == 0) {',
        '        isPrime = false;',
        '        break;',
        '      }',
        '    }',
        '    System.out.println(num + (isPrime ? " este prim." : " nu este prim."));',
        '    input.close();',
        '  }',
        '}',
      ],
    },
    {
      id: 3,
      lines: [
        'import java.util.Scanner;',
        'public class ReverseString {',
        '  public static void main(String[] args) {',
        '    Scanner input = new Scanner(System.in);',
        '    System.out.print("Introdu un text: ");',
        '    String text = input.nextLine();',
        '    String reversed = "";',
        '    for (int i = text.length() - 1; i >= 0; i--) {',
        '      reversed += text.charAt(i);',
        '    }',
        '    System.out.println("Textul inversat: " + reversed);',
        '    input.close();',
        '  }',
        '}',
      ],
    },
    {
      id: 4,
      lines: [
        'import java.util.Scanner;',
        'public class AverageCalculator {',
        '  public static void main(String[] args) {',
        '    Scanner input = new Scanner(System.in);',
        '    System.out.print("Câte numere vei introduce? ");',
        '    int count = input.nextInt();',
        '    double sum = 0;',
        '    for (int i = 1; i <= count; i++) {',
        '      System.out.print("Număr " + i + ": ");',
        '      sum += input.nextDouble();',
        '    }',
        '    double average = sum / count;',
        '    System.out.println("Media este: " + average);',
        '    input.close();',
        '  }',
        '}',
      ],
    },
    {
      id: 5,
      lines: [
        'import java.util.Scanner;',
        'public class VowelCounter {',
        '  public static void main(String[] args) {',
        '    Scanner input = new Scanner(System.in);',
        '    System.out.print("Introdu un șir: ");',
        '    String str = input.nextLine().toLowerCase();',
        '    int count = 0;',
        '    for (int i = 0; i < str.length(); i++) {',
        '      if ("aeiou".contains(String.valueOf(str.charAt(i)))) {',
        '        count++;',
        '      }',
        '    }',
        '    System.out.println("Număr de vocale: " + count);',
        '    input.close();',
        '  }',
        '}',
      ],
    },
  ];
  
  export default snippets;
  